# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec Jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via the {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jeevan Shrestha
email: shresthajeevan777@gmail.com
description:  "Robotics and Embedded Electronics Engineer"
url: "https://jeevan-git.github.io"
twitter_username: kaurska07
github_username: jeevan-git
linkiden_username: jeevan-shrestha
minimal_mistakes_skin: "default"
search: true

twitter:
  username: "kaurska07"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Outputting
permalink: /:year/:month/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kathmandu



og_image: /images/default_post_image.jpg

include:
  - _pages
  
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jeevan Shrestha"
  avatar : "/images/Jeevan_avatar3.jpg"
  bio    : "Robotics and Embedded Electronics Engineer"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kaurska07"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeevan-git"
    - label: "Linkedin"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/jeevan-shrestha-832413161/"
    - label: "Youtube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCpYuXpvJxp3C5-Fdnrzkqjg"
    # - label: "Subscribe"
    #   icon: "fas fa-fw fa-envelope"
    #   url: "https://feedburner.google.com/fb/a/mailverify?uri=MadanBaduwal&amp;loc=en_US"
#    - label: "Email"
#      icon: "fab fa-envelope"
#      url: "mailto:meamitkc@gmail.com" 
#    - label: "Feed"
#      icon: "fab fa-fw fa-globe"
#      url: "/feed.xml"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kaurska07"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeevan-git"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "images/"
    values:
      image: true

collections:
  projects:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
repository: "jeevan-git/jeevan-git.github.io"

#google-site-verification: "7PTmUxxTjmF3fgdhOmPbB5uNjkzCLD5vhItBRnJJSZY"  # get from google search console

social:
  type:  Person
  name:  Jeevan Shrestha
  links:
    - "https://twitter.com/kaurska07"
    - "https://github.com/jeevan-git"
    - "https://www.linkedin.com/in/jeevan-shrestha-832413161/"
    - "https://www.youtube.com/channel/UCpYuXpvJxp3C5-Fdnrzkqjg"
#    - "https://stackoverflow.com/users/13783264"

google:
  search_engine_id: 8f72b932abdeba82d
  
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-25459974-1"
    anonymize_ip: false
